name: DupeLibrary
version: '1.1'
main: com.necmi.dupelibrary.DupeLibrary
api-version: '1.21'
authors: [ Necmi ]
description: A Dupe Method Library
commands:
  dupelibrary:
    description: DupeLibrary yönetim komutu
    usage: /dupelibrary help
